# Data manipulation
Acquires data and reads it into the computer for processing

## First
tensor

In [1]:
import torch
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
x.shape

torch.Size([12])

In [3]:
x.numel()

12

In [4]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
torch.randn(3,4)  #Random sampling in a standard Gassian distribution

tensor([[-0.4196,  0.6014, -0.4505,  2.0108],
        [ 1.1862, -0.7113, -0.4538,  0.0430],
        [ 1.4146, -0.0728, -1.8363,  0.0365]])

In [8]:
torch.tensor([[1,2,3,4],[1,3,4,5],[2,3,1,4]])

tensor([[1, 2, 3, 4],
        [1, 3, 4, 5],
        [2, 3, 1, 4]])

In [9]:
x=torch.arange(5)
y=torch.tensor([4,1,2,3,1])
x+y,x-y,x*y,x/y,x**y

(tensor([4, 2, 4, 6, 5]),
 tensor([-4,  0,  0,  0,  3]),
 tensor([0, 1, 4, 9, 4]),
 tensor([0., 1., 1., 1., 4.]),
 tensor([ 0,  1,  4, 27,  4]))

In [10]:
torch.exp(x) #find the power sign

tensor([ 1.0000,  2.7183,  7.3891, 20.0855, 54.5981])

In [11]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[1,3,5,2],[1,2,3,2],[1,5,3,9]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  3.,  5.,  2.],
         [ 1.,  2.,  3.,  2.],
         [ 1.,  5.,  3.,  9.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  3.,  5.,  2.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  2.],
         [ 8.,  9., 10., 11.,  1.,  5.,  3.,  9.]]))

In [12]:
X.sum()

tensor(66.)

In [13]:
#Broadcast Mechanism
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [15]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))